apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-jacb
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-blar-tenant/rhtap-demo-app/hacbs-test-project-jacb@sha256:c02efb60e65f12ec57b0d900cb8fefc813be8a0c356f91850e91824bd42e8c96
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
